# Generated by Django 4.0.4 on 2022-04-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_comments_options_alter_witzuser_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_posted']},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='zeef', upload_to=''),
        ),
    ]
