# Generated by Django 3.2.6 on 2022-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220422_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witzuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Other', 'Other'), (None, 'Select one only')], default=' ', max_length=50),
        ),
    ]
