# Generated by Django 4.0.4 on 2022-04-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_comments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='witzuser',
            name='profile_pic',
            field=models.ImageField(default='someimg', upload_to='static/media/profile_pic'),
        ),
    ]
