# Generated by Django 4.0.4 on 2022-04-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_witzuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witzuser',
            name='profile_pic',
            field=models.ImageField(default='static/media/profile_pic/default.jpeg', upload_to='static/media/profile_pic'),
        ),
    ]
