# Generated by Django 4.0.4 on 2022-04-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_witzuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witzuser',
            name='profile_pic',
            field=models.ImageField(default='default.jpeg', upload_to='profile_pic/'),
        ),
    ]
