# Generated by Django 4.0.4 on 2022-05-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pictures',
            field=models.ImageField(default='default.jpeg', upload_to='post_pics/'),
        ),
    ]
