# Generated by Django 4.0.4 on 2022-05-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_post_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ImageField(default=' ', upload_to='post_pics/'),
        ),
    ]
