# Generated by Django 4.0.4 on 2022-05-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_post_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pictures',
            field=models.ImageField(blank=True, upload_to='post_pics/'),
        ),
        migrations.AlterField(
            model_name='witzuser',
            name='profile_pic',
            field=models.ImageField(default='default_pic.jpg', upload_to='profile_pic/'),
        ),
    ]
